name: flutter_portfolio
description: "Portfolio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_riverpod: 2.4.10
  flutter_animate: 4.5.0
  url_launcher: 6.2.6
  google_fonts: 6.1.0
  responsive_framework: 1.1.1
  font_awesome_flutter: 10.4.0
  flutter_staggered_animations: 1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: 0.18.1
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/images/
